#!/bin/bash

# Check if the correct number of arguments are provided
if [ "$#" -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign the arguments to variables
FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Use scp to transfer the file to the user's home directory on the server
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "$USERNAME@$IP:~/"

# Check the exit status of the scp command
if [ "$?" -eq 0 ]; then
  echo "File successfully transferred to $IP"
else
  echo "Error: File transfer failed"
fi
