#!usr/bin/env/bash

if [ "$#" -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi
file_to_transfer="$1"
server_ip="$2"
username="$4"
ssh_key="$4"
scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_to_transfer" "$username@$server_ip:~/"
if [ "$?" -eq 0 ]; then
  echo "File successfully transferred to $IP"
else
  echo "Error: File transfer failed"
fi
