#!/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header

sudo apt-get update
sudo apt-get install -y nginx

#code to redirect a specific endpoint
echo "Hello World!" | sudo tee /var/www/html/index.html

#code for redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.afriyie.tech permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# code to create error page and add a redirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

#custom HTTP response header
sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#syntax errors test
sudo nginx -t

#restart afterwards
sudo service nginx restart
